// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcAvhs8Z0w92-VlGYu52F0WEyzaH9S51o',
    appId: '1:986180129435:web:dc0010ffa21f4adb37ec3e',
    messagingSenderId: '986180129435',
    projectId: 'disease-detection-60cb5',
    authDomain: 'disease-detection-60cb5.firebaseapp.com',
    storageBucket: 'disease-detection-60cb5.firebasestorage.app',
    measurementId: 'G-W6LE5MQL1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYkar6reQeuULC_-e1vO-VnVpvGNlRYZ4',
    appId: '1:986180129435:android:1cba5b62a18016b137ec3e',
    messagingSenderId: '986180129435',
    projectId: 'disease-detection-60cb5',
    storageBucket: 'disease-detection-60cb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ5t3_mP3vohBS-yDCV11UcmO10It1P4k',
    appId: '1:986180129435:ios:ae130a127fb33bd337ec3e',
    messagingSenderId: '986180129435',
    projectId: 'disease-detection-60cb5',
    storageBucket: 'disease-detection-60cb5.firebasestorage.app',
    iosBundleId: 'com.example.plantDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ5t3_mP3vohBS-yDCV11UcmO10It1P4k',
    appId: '1:986180129435:ios:ae130a127fb33bd337ec3e',
    messagingSenderId: '986180129435',
    projectId: 'disease-detection-60cb5',
    storageBucket: 'disease-detection-60cb5.firebasestorage.app',
    iosBundleId: 'com.example.plantDetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcAvhs8Z0w92-VlGYu52F0WEyzaH9S51o',
    appId: '1:986180129435:web:217517bea0f0352737ec3e',
    messagingSenderId: '986180129435',
    projectId: 'disease-detection-60cb5',
    authDomain: 'disease-detection-60cb5.firebaseapp.com',
    storageBucket: 'disease-detection-60cb5.firebasestorage.app',
    measurementId: 'G-X7365L2N32',
  );
}
